### PR TITLE
Fix Number reversed when using RTL localization.

### PR DESCRIPTION
**Pull request by Danzo7**
### :bug: Bug:
- when using a RTL localization the number appears reversed, for example if you have `count=24` It Will appear as `42` and when you press the button it will go to `52` .
### :dart: Reason:
- When using an Arabic Localization for examples, Flutter will automatically reverse Row items so the first item will be the last.
### :gear: Fix:
- To fix this you need to force the row of numbers to use LTR by adding `Directionality`

### CODE REVIEW

**Comment by zmtzawqlp** [comment]
thanks your contribution. public textDirection: TextDirection.ltr as property will better.

**Comment by Danzo7** [comment]
Hi @zmtzawqlp Hope you are doing great! 

This will work too, but I would rather keep it like that as there is no language that read numerals from right to left so I don't think its make sense as property, Also we just use it to reverse back the row of numbers and having it as property that can cause conflict with the meaning of `textDirection` as we don't actually modify the direction of text , don't you agree?

**Comment by zmtzawqlp** [comment]
In fact，user can use like as following code:
Directionality(child:LikeButton)
I don't think it's good to force it left to right, we should provide an chance for user. so i don't this pr is necessary。thanks

**Comment by zmtzawqlp** [comment]
> Hi @zmtzawqlp Hope you are doing great!
> 
> This will work too, but I would rather keep it like that as there is no language that read numerals from right to left so I don't think its make sense as property, Also we just use it to reverse back the row of numbers and having it as property that can cause conflict with the meaning of `textDirection` as we don't actually modify the direction of text , don't you agree?

ok, i got it, thanks

**Pull request merged**
