### PR TITLE
code trigger tap function

### PR DESCRIPTION
**Pull request by Aobanana-chan**
增加特性:
1.增加回调获取onTap函数
2.可选在播放动画时是否执行onTap
3.增加不使用Globalkey调用onTap的Demo

### CODE REVIEW

**Comment by zmtzawqlp** [comment]
thanks for your  contribution but i have nothing to say. I suggest you to take a look at https://flutter.cn first.

**Comment by Aobanana-chan** [comment]
emmm. Do you mean my code doesn't work?

**Comment by zmtzawqlp** [comment]
if it's just need to be runnable, there are more ways to do this.

**Comment by Aobanana-chan** [comment]
I heard that using globalkey is expensive. If there are other options, try to avoid using it. I just want we can trigger Tap without using globalkey.  
And in my case,if I tap agree button and disagree button(we can't agree and disagree at the same time),Tap is disabled because of
```
if (_controller!.isAnimating || _likeCountController!.isAnimating) {
      return;
}
```
So I add [disableTapWhenAnimating] and [rapidTriggerTap] to let user to decide it.

**Pull request closed without merging**
