### PR TITLE
public some state information

### PR DESCRIPTION
**Pull request by XuanTung95**
- add getter for _isLiked and _controller
- add method runAnimation()

### CODE REVIEW

**Comment by zmtzawqlp** [comment]
add this for which case?

**Comment by XuanTung95** [comment]
> add this for which case?

1 - to check the current state
2 - run the animation programmatically

**Comment by zmtzawqlp** [comment]
i don't think they are necessary, two cases are supported simply with current code.

**Comment by XuanTung95** [comment]
1 - I don't know how to get _isLiked with the current code
2 - I know onTap can run the animation but only when _isLiked = false, when _isLiked = true I must call onTap 2 times to run it? and as 1, I don't know the current value of _isLiked.

**Comment by zmtzawqlp** [comment]
1. isLiked is from your side, and is changed in onTap
2. i can't think out when do you need to run animation without change isLiked.

**Comment by XuanTung95** [comment]
2. I want to use it as an Icon with animation, and I can show the animation at will. The value of _isLiked is ignored for me and user don't need to tap on it.

**Comment by zmtzawqlp** [comment]
so it is special requirement, you can fork master branch and change it as you wish, thanks

**Pull request closed without merging**
